server:
    port: 14004

spring:
    rabbitmq:
        host: localhost
        username: admin
        password: admin
        port: 5672
    
    application:
        name: question-service
    data:
        jdbc:
            dialect: postgresql
    datasource:
        url: jdbc:postgresql://localhost:5432/questionarium
        password: postgres
        username: postgres

    jpa:
        show-sql: true
        hibernate:
            ddl-auto: create-drop

logging:
    level:
        org:
            springframework:
                security: TRACE