
server:
  port: 8084

spring:
  rabbitmq:
    host: localhost
    password: admin
    username: admin
    port: 5672
  mail:
    host: smtp.gmail.com
    port: 587
    username: samueldzsantos@gmail.com
    password: ddoj qjxl kgaa ggdo
    default-encoding: UTF-8
    properties:
      mail:
        mime:
            charset: UTF
        smtp:
          writetimeout: 10000
          connectiontimeout: 10000
          timeout: 10000
          auth: true
          starttls:
            enable: true
            required: true
