server:
  port: 9297
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/SamuelDzSantos/questionarium-config.git
          clone-on-start: true
  application:
    name: config-service

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.uri:localhost:8761}/eureka/
      
