spring:
    application:
        name: gateway
    cloud:
      gateway:
        routes:
        - id: auth
          uri: 
          predicates: http://localhost:8082
            - Path=/user
      discovery:
        enabled: true
server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://${eureka.uri:localhost:8083}/eureka/
 
