server:
  port: 8080

spring:
  application:
    name: api-service
  cloud:
    discovery:
      enabled: true
    gateway:
        routes:
        - id: user-service
          uri: lb://user-service
          predicates:
          - Path=/users/*      
      
        
logging:
  level:
    org:
      springframework:
        security: TRACE


jwt:
  secret: 653F65CCFD82585F3983825EDA89D123
  expiration: 86400
