server:
  port: 8082


eureka:
  client:
    service-url:
      defaultZone: http://${eureka.uri:localhost:8083}/eureka/

spring:
    application:
        name: auth
    datasource:
        url: jdbc:postgresql://localhost:5432/questionarium
        username: postgres
        password: postgres
    jpa:
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect

