server:
  port: 8082

spring:
  
  rabbitmq:
    host: localhost
    password: test
    username: test
    port: 5672

  application:
    name: user-service
  data:
    jdbc:
      dialect: postgresql
  datasource:
    url: jdbc:postgresql://localhost:5432/questionarium
    password: postgres
    username: postgres

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop

jwt:
  secret: 653F65CCFD82585F3983825EDA89D123
  expiration: 86400

